In [1]:
print("Hello world")

Hello world

## Problem Statement

XYZ company 2014-2018 sales data to iddentify key revenue and profit drivers across products , channelsand regions uncover seasional treands and outliers and align preformance aganest budgets , Use these insights to optimize pricing , promotions and market expansion for sustainable growth and reduced concentration risk

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Reading all sheets in excel file

XL_sheet = pd.read_excel("Regional Sales Dataset.xlsx" , sheet_name= None)

In [4]:
XL_sheet

{'Sales Orders':         OrderNumber  OrderDate  Customer Name Index      Channel  \
 0       SO - 000225 2014-01-01                  126    Wholesale
 1      SO - 0003378 2014-01-01                   96  Distributor
 2      SO - 0005126 2014-01-01                    8    Wholesale
 3      SO - 0005614 2014-01-01                   42       Export
 4      SO - 0005781 2014-01-01                   73    Wholesale
 ...             ...        ...                  ...          ...
 64099  SO - 0007573 2018-02-28                   74    Wholesale
 64100  SO - 0007706 2018-02-28                   51       Export
 64101  SO - 0007718 2018-02-28                  136  Distributor
 64102  SO - 0008084 2018-02-28                  158  Distributor
 64103  SO - 0008654 2018-02-28                   22  Distributor

       Currency Code Warehouse Code  Delivery Region Index  \
 0               USD         AXW291                    364
 1               USD         AXW291                    488
 2               USD         AXW291                    155
 3               USD         AXW291                    473
 4               USD         AXW291                    256
 ...             ...            ...                    ...
 64099           USD         AXW291                    825
 64100           USD         NXH382                    444
 64101           USD         AXW291                    312
 64102           USD         AXW291                    737
 64103           USD         AXW291                    807

        Product Description Index  Order Quantity  Unit Price  Line Total  \
 0                             27               6      2499.1     14994.6
 1                             20              11      2351.7     25868.7
 2                             26               6       978.2      5869.2
 3                              7               7      2338.3     16368.1
 4                              8               8      2291.4     18331.2
 ...                          ...             ...         ...         ...
 64099                         26              12      1815.7     21788.4
 64100                         21               6       864.3      5185.8
 64101                         13              11      3953.0     43483.0
 64102                         20               7      3959.7     27717.9
 64103                         15               8       998.3      7986.4

        Total Unit Cost
 0             1824.343
 1             1269.918
 2              684.740
 3             1028.852
 4             1260.270
 ...                ...
 64099          980.478
 64100          579.081
 64101         2648.510
 64102         2930.178
 64103          848.555

 [64104 rows x 12 columns],
 'Customers':      Customer Index Customer Names
 0                 1  Geiss Company
 1                 2  Jaxbean Group
 2                 3     Ascend Ltd
 3                 4      Eire Corp
 4                 5   Blogtags Ltd
 ..              ...            ...
 170             171   Accord Group
 171             172   BB17 Company
 172             173          H Ltd
 173             174   Tekfly Group
 174             175   SHISEIDO Ltd

 [175 rows x 2 columns],
 'Regions':       id        name                                   county state_code  \
 0      1      Auburn                               Lee County         AL
 1      2  Birmingham           Shelby County/Jefferson County         AL
 2      3     Decatur           Limestone County/Morgan County         AL
 3      4      Dothan  Dale County/Houston County/Henry County         AL
 4      5      Hoover           Shelby County/Jefferson County         AL
 ..   ...         ...                                      ...        ...
 989  990      Racine                            Racine County         WI
 990  991    Waukesha                          Waukesha County         WI
 991  992  West Allis                         Milwaukee County         WI
 992  993      Casper                           Natrona County         WY
 993  994    Cheyenne                           Laramie County         WY

          state  type  latitude  longitude  area_code  population  households  \
 0      Alabama  City  32.60986  -85.48078        334       62059       21767
 1      Alabama  City  33.52744  -86.79905        205      212461       89972
 2      Alabama  City  34.57332  -86.99214        256       55437       22294
 3      Alabama  City  31.23370  -85.40682        334       68567       25913
 4      Alabama  City  33.37695  -86.80558        205       84848       32789
 ..         ...   ...       ...        ...        ...         ...         ...
 989  Wisconsin  City  42.72613  -87.78285        262       77742       29851
 990  Wisconsin  City  43.01168  -88.23148        262       71970       28331
 991  Wisconsin  City  43.01668  -88.00703        414       60620       27457
 992    Wyoming  City  42.86663 -106.31308        307       60285       23814
 993    Wyoming  City  41.13998 -104.82025        307       63335       25130

      median_income  land_area  water_area        time_zone
 0            38342  152375113     2646161  America/Chicago
 1            31061  378353942     6591013  America/Chicago
 2            41496  141006257    17594716  America/Chicago
 3            42426  232166237      835468  America/Chicago
 4            77146  122016784     2553332  America/Chicago
 ..             ...        ...         ...              ...
 989          41455   40111757     8282116  America/Chicago
 990          59547   65856921      700602  America/Chicago
 991          45221   29480532       60789  America/Chicago
 992          57790   68507280      911081   America/Denver
 993          58219   69964749      282335   America/Denver

 [994 rows x 15 columns],
 'State Regions':        Column1               Column2    Column3
 0   State Code                 State     Region
 1           AL               Alabama      South
 2           AR              Arkansas      South
 3           AZ               Arizona       West
 4           CA            California       West
 5           CO              Colorado       West
 6           CT           Connecticut  Northeast
 7           DC  District of Columbia      South
 8           DE              Delaware      South
 9           FL               Florida      South
 10          GA               Georgia      South
 11          HI                Hawaii       West
 12          IA                  Iowa    Midwest
 13          ID                 Idaho       West
 14          IL              Illinois    Midwest
 15          IN               Indiana    Midwest
 16          KS                Kansas    Midwest
 17          KY              Kentucky      South
 18          LA             Louisiana      South
 19          MA         Massachusetts  Northeast
 20          MD              Maryland      South
 21          ME                 Maine  Northeast
 22          MI              Michigan    Midwest
 23          MN             Minnesota    Midwest
 24          MO              Missouri    Midwest
 25          MS           Mississippi      South
 26          MT               Montana       West
 27          NC        North Carolina      South
 28          ND          North Dakota    Midwest
 29          NE              Nebraska    Midwest
 30          NH         New Hampshire  Northeast
 31          NJ            New Jersey  Northeast
 32          NM            New Mexico       West
 33          NV                Nevada       West
 34          NY              New York  Northeast
 35          OH                  Ohio    Midwest
 36          OK              Oklahoma      South
 37          OR                Oregon       West
 38          PA          Pennsylvania  Northeast
 39          RI          Rhode Island  Northeast
 40          SC        South Carolina      South
 41          SD          South Dakota    Midwest
 42          TN             Tennessee      South
 43          TX                 Texas      South
 44          UT                  Utah       West
 45          VA              Virginia      South
 46          WA            Washington       West
 47          WI             Wisconsin    Midwest
 48          WY               Wyoming       West,
 'Products':     Index Product Name
 0       1    Product 1
 1       2    Product 2
 2       3    Product 3
 3       4    Product 4
 4       5    Product 5
 5       6    Product 6
 6       7    Product 7
 7       8    Product 8
 8       9    Product 9
 9      10   Product 10
 10     11   Product 11
 11     12   Product 12
 12     13   Product 13
 13     14   Product 14
 14     15   Product 15
 15     16   Product 16
 16     17   Product 17
 17     18   Product 18
 18     19   Product 19
 19     20   Product 20
 20     21   Product 21
 21     22   Product 22
 22     23   Product 23
 23     24   Product 24
 24     25   Product 25
 25     26   Product 26
 26     27   Product 27
 27     28   Product 28
 28     29   Product 29
 29     30   Product 30,
 '2017 Budgets':    Product Name  2017 Budgets
 0     Product 1   3016489.209
 1     Product 2   3050087.565
 2     Product 3   2642352.432
 3     Product 4   2885560.824
 4     Product 5   3925424.542
 5     Product 6   1672229.416
 6     Product 7    889737.555
 7     Product 8   1085037.329
 8     Product 9    710415.405
 9    Product 10    864331.624
 10   Product 11   1230458.484
 11   Product 12   1356976.996
 12   Product 13   3720639.645
 13   Product 14   4028698.409
 14   Product 15   3299478.315
 15   Product 16   2062061.144
 16   Product 17   2119616.824
 17   Product 18   2309499.045
 18   Product 19   1645841.600
 19   Product 20   2067108.120
 20   Product 21    959899.218
 21   Product 22    663601.902
 22   Product 23   1135815.758
 23   Product 24    756557.970
 24   Product 25   5342315.484
 25   Product 26   5685138.270
 26   Product 27    964940.231
 27   Product 28   1003867.767
 28   Product 29    594471.570
 29   Product 30   1011609.684}

In [5]:
df_lst =[]
for i in XL_sheet:
    print(i)
    df_lst.append(i)

print(df_lst)

Sales Orders
Customers
Regions
State Regions
Products
2017 Budgets
['Sales Orders', 'Customers', 'Regions', 'State Regions', 'Products', '2017 Budgets']

In [6]:
# Extracting all sheets , Assigning sheets to named dataframes

df_sales = XL_sheet['Sales Orders']
df_Customers = XL_sheet['Customers']
df_Regions = XL_sheet['Regions']
df_state_regions = XL_sheet['State Regions']
df_Products = XL_sheet['Products']
df_Budget = XL_sheet["2017 Budgets"]

# Data understanding

### shape

In [7]:
print(df_sales.shape)
print(df_Customers.shape)
print(df_Regions.shape)
print(df_state_regions.shape)
print(df_Products.shape)
print(df_Budget.shape)

(64104, 12)
(175, 2)
(994, 15)
(49, 3)
(30, 2)
(30, 2)

In [8]:
lst_dfs = [df_sales, df_Customers, df_Regions, df_state_regions, df_Products, df_Budget]

for i in lst_dfs:
    print(f" shape is {i.shape}")

 shape is (64104, 12)
 shape is (175, 2)
 shape is (994, 15)
 shape is (49, 3)
 shape is (30, 2)
 shape is (30, 2)

In [9]:
dfs = {
    "df_sales": df_sales,
    "df_Customers": df_Customers,
    "df_Regions": df_Regions,
    "df_state_regions": df_state_regions,
    "df_Products": df_Products,
    "df_Budget": df_Budget
}

for name, df in dfs.items():
    print(f"{name} shape is {df.shape}")

df_sales shape is (64104, 12)
df_Customers shape is (175, 2)
df_Regions shape is (994, 15)
df_state_regions shape is (49, 3)
df_Products shape is (30, 2)
df_Budget shape is (30, 2)

### info()

In [10]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(4)
memory usage: 5.9+ MB

In [11]:
df_Regions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             994 non-null    int64
 1   name           994 non-null    object
 2   county         994 non-null    object
 3   state_code     994 non-null    object
 4   state          994 non-null    object
 5   type           994 non-null    object
 6   latitude       994 non-null    float64
 7   longitude      994 non-null    float64
 8   area_code      994 non-null    int64
 9   population     994 non-null    int64
 10  households     994 non-null    int64
 11  median_income  994 non-null    int64
 12  land_area      994 non-null    int64
 13  water_area     994 non-null    int64
 14  time_zone      994 non-null    object
dtypes: float64(2), int64(7), object(6)
memory usage: 116.6+ KB

In [12]:
df_Budget.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  30 non-null     object
 1   2017 Budgets  30 non-null     float64
dtypes: float64(1), object(1)
memory usage: 612.0+ bytes

In [13]:
df_Customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer Index  175 non-null    int64
 1   Customer Names  175 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.9+ KB

In [14]:
df_state_regions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  49 non-null     object
 1   Column2  49 non-null     object
 2   Column3  49 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB

In [15]:
df_Budget.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  30 non-null     object
 1   2017 Budgets  30 non-null     float64
dtypes: float64(1), object(1)
memory usage: 612.0+ bytes

### columns of each dataframe

In [16]:
df_sales.columns

Index(['OrderNumber', 'OrderDate', 'Customer Name Index', 'Channel',
       'Currency Code', 'Warehouse Code', 'Delivery Region Index',
       'Product Description Index', 'Order Quantity', 'Unit Price',
       'Line Total', 'Total Unit Cost'],
      dtype='object')

In [17]:
df_Customers.columns

Index(['Customer Index', 'Customer Names'], dtype='object')

In [18]:
df_Products.columns

Index(['Index', 'Product Name'], dtype='object')

In [19]:
df_Budget.columns

Index(['Product Name', '2017 Budgets'], dtype='object')

In [20]:
df_Regions.columns

Index(['id', 'name', 'county', 'state_code', 'state', 'type', 'latitude',
       'longitude', 'area_code', 'population', 'households', 'median_income',
       'land_area', 'water_area', 'time_zone'],
      dtype='object')

In [21]:
df_state_regions.columns   ## need to change the column name

Index(['Column1', 'Column2', 'Column3'], dtype='object')

In [22]:
df_state_regions.head()

      Column1     Column2 Column3
0  State Code       State  Region
1          AL     Alabama   South
2          AR    Arkansas   South
3          AZ     Arizona    West
4          CA  California    West

In [23]:
df_state_regions.columns = df_state_regions.iloc[0]   # set first row as header
df_state_regions = df_state_regions[1:]               # remove the first row from data
df_state_regions = df_state_regions.reset_index(drop=True)

In [24]:
df_state_regions.columns

Index(['State Code', 'State', 'Region'], dtype='object', name=0)

### head() all dataframes

In [25]:
df_sales.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270

In [26]:
df_Products.head()

   Index Product Name
0      1    Product 1
1      2    Product 2
2      3    Product 3
3      4    Product 4
4      5    Product 5

In [27]:
df_Budget.head()

  Product Name  2017 Budgets
0    Product 1   3016489.209
1    Product 2   3050087.565
2    Product 3   2642352.432
3    Product 4   2885560.824
4    Product 5   3925424.542

In [28]:
df_Regions.head()

,id,name,county,state_code,state,type,latitude,longitude,area_code,population,households,median_income,land_area,water_area,time_zone
0,1,Auburn,Lee County,AL,Alabama,City,32.60986,-85.48078,334,62059,21767,38342,152375113,2646161,America/Chicago
1,2,Birmingham,Shelby County/Jefferson County,AL,Alabama,City,33.52744,-86.79905,205,212461,89972,31061,378353942,6591013,America/Chicago
2,3,Decatur,Limestone County/Morgan County,AL,Alabama,City,34.57332,-86.99214,256,55437,22294,41496,141006257,17594716,America/Chicago
3,4,Dothan,Dale County/Houston County/Henry County,AL,Alabama,City,31.23370,-85.40682,334,68567,25913,42426,232166237,835468,America/Chicago
4,5,Hoover,Shelby County/Jefferson County,AL,Alabama,City,33.37695,-86.80558,205,84848,32789,77146,122016784,2553332,America/Chicago

In [29]:
df_state_regions.head()

0 State Code       State Region
0         AL     Alabama  South
1         AR    Arkansas  South
2         AZ     Arizona   West
3         CA  California   West
4         CO    Colorado   West

In [30]:
df_Customers.head()

   Customer Index Customer Names
0               1  Geiss Company
1               2  Jaxbean Group
2               3     Ascend Ltd
3               4      Eire Corp
4               5   Blogtags Ltd

### missing Values

In [31]:
print("Total null values in df_sales: ",df_sales.isnull().sum().sum())
df_sales.isnull().sum()

Total null values in df_sales:  0

OrderNumber                  0
OrderDate                    0
Customer Name Index          0
Channel                      0
Currency Code                0
Warehouse Code               0
Delivery Region Index        0
Product Description Index    0
Order Quantity               0
Unit Price                   0
Line Total                   0
Total Unit Cost              0
dtype: int64

In [32]:
print("total null values in df_Regions:",df_Regions.isnull().sum().sum())
df_Regions.isnull().sum()

total null values in df_Regions: 0

id               0
name             0
county           0
state_code       0
state            0
type             0
latitude         0
longitude        0
area_code        0
population       0
households       0
median_income    0
land_area        0
water_area       0
time_zone        0
dtype: int64

In [33]:
print("Total null values in  df_Budget :",df_Budget.isnull().sum().sum())
df_Budget.isnull().sum()

Total null values in  df_Budget : 0

Product Name    0
2017 Budgets    0
dtype: int64

In [34]:
print("total null values in df_Customers: ",df_Customers.isnull().sum().sum())
df_Customers.isnull().sum()

total null values in df_Customers:  0

Customer Index    0
Customer Names    0
dtype: int64

In [35]:
print("Total null values in df_Products: ",df_Products.isnull().sum().sum())
df_Products.isnull().sum()

Total null values in df_Products:  0

Index           0
Product Name    0
dtype: int64

In [36]:
print("total null values df_state_regions:",df_state_regions.isnull().sum().sum())
df_state_regions.isnull().sum()

total null values df_state_regions: 0

0
State Code    0
State         0
Region        0
dtype: int64

#### duplicate values

In [37]:
df_sales.duplicated().sum()

np.int64(0)

In [38]:
df_state_regions.duplicated().sum()

np.int64(0)

In [39]:
df_Regions.duplicated().sum()

np.int64(0)

In [40]:
df_Budget.duplicated().sum()

np.int64(0)

In [41]:
df_Customers.duplicated().sum()

np.int64(0)

In [42]:
df_Products.duplicated().sum()

np.int64(0)

### Printing shape, columns, missing values, duplicates, head

In [43]:
dfs = {
    "df_sales": df_sales,
    "df_Customers": df_Customers,
    "df_Regions": df_Regions,
    "df_state_regions": df_state_regions,
    "df_Products": df_Products,
    "df_Budget": df_Budget
}

In [44]:
for name, df in dfs.items():
    print(f"\n📊 DataFrame: {name}")
    print("="*60)

    print("Shape :", df.shape)

    print("\nColumns :")
    print(df.columns.tolist())

    print("\nMissing Values :")
    print(df.isnull().sum())

    print("\nDuplicate Rows :", df.duplicated().sum())

    print("\nHead :")
    print(df.head())

    print("\n" + "#"*60)

📊 DataFrame: df_sales
============================================================
Shape : (64104, 12)

Columns :
['OrderNumber', 'OrderDate', 'Customer Name Index', 'Channel', 'Currency Code', 'Warehouse Code', 'Delivery Region Index', 'Product Description Index', 'Order Quantity', 'Unit Price', 'Line Total', 'Total Unit Cost']

Missing Values :
OrderNumber                  0
OrderDate                    0
Customer Name Index          0
Channel                      0
Currency Code                0
Warehouse Code               0
Delivery Region Index        0
Product Description Index    0
Order Quantity               0
Unit Price                   0
Line Total                   0
Total Unit Cost              0
dtype: int64

Duplicate Rows : 0

Head :
    OrderNumber  OrderDate  Customer Name Index      Channel Currency Code  \
0   SO - 000225 2014-01-01                  126    Wholesale           USD
1  SO - 0003378 2014-01-01                   96  Distributor           USD
2  SO - 0005126 2014-01-01                    8    Wholesale           USD
3  SO - 0005614 2014-01-01                   42       Export           USD
4  SO - 0005781 2014-01-01                   73    Wholesale           USD

  Warehouse Code  Delivery Region Index  Product Description Index  \
0         AXW291                    364                         27
1         AXW291                    488                         20
2         AXW291                    155                         26
3         AXW291                    473                          7
4         AXW291                    256                          8

   Order Quantity  Unit Price  Line Total  Total Unit Cost
0               6      2499.1     14994.6         1824.343
1              11      2351.7     25868.7         1269.918
2               6       978.2      5869.2          684.740
3               7      2338.3     16368.1         1028.852
4               8      2291.4     18331.2         1260.270

############################################################

📊 DataFrame: df_Customers
============================================================
Shape : (175, 2)

Columns :
['Customer Index', 'Customer Names']

Missing Values :
Customer Index    0
Customer Names    0
dtype: int64

Duplicate Rows : 0

Head :
   Customer Index Customer Names
0               1  Geiss Company
1               2  Jaxbean Group
2               3     Ascend Ltd
3               4      Eire Corp
4               5   Blogtags Ltd

############################################################

📊 DataFrame: df_Regions
============================================================
Shape : (994, 15)

Columns :
['id', 'name', 'county', 'state_code', 'state', 'type', 'latitude', 'longitude', 'area_code', 'population', 'households', 'median_income', 'land_area', 'water_area', 'time_zone']

Missing Values :
id               0
name             0
county           0
state_code       0
state            0
type             0
latitude         0
longitude        0
area_code        0
population       0
households       0
median_income    0
land_area        0
water_area       0
time_zone        0
dtype: int64

Duplicate Rows : 0

Head :
   id        name                                   county state_code  \
0   1      Auburn                               Lee County         AL
1   2  Birmingham           Shelby County/Jefferson County         AL
2   3     Decatur           Limestone County/Morgan County         AL
3   4      Dothan  Dale County/Houston County/Henry County         AL
4   5      Hoover           Shelby County/Jefferson County         AL

     state  type  latitude  longitude  area_code  population  households  \
0  Alabama  City  32.60986  -85.48078        334       62059       21767
1  Alabama  City  33.52744  -86.79905        205      212461       89972
2  Alabama  City  34.57332  -86.99214        256       55437       22294
3  Alabama  City  31.23370  -85.40682        334       68567       25913
4  Alabama  City  33.37695  -86.80558        205       84848       32789

   median_income  land_area  water_area        time_zone
0          38342  152375113     2646161  America/Chicago
1          31061  378353942     6591013  America/Chicago
2          41496  141006257    17594716  America/Chicago
3          42426  232166237      835468  America/Chicago
4          77146  122016784     2553332  America/Chicago

############################################################

📊 DataFrame: df_state_regions
============================================================
Shape : (48, 3)

Columns :
['State Code', 'State', 'Region']

Missing Values :
0
State Code    0
State         0
Region        0
dtype: int64

Duplicate Rows : 0

Head :
0 State Code       State Region
0         AL     Alabama  South
1         AR    Arkansas  South
2         AZ     Arizona   West
3         CA  California   West
4         CO    Colorado   West

############################################################

📊 DataFrame: df_Products
============================================================
Shape : (30, 2)

Columns :
['Index', 'Product Name']

Missing Values :
Index           0
Product Name    0
dtype: int64

Duplicate Rows : 0

Head :
   Index Product Name
0      1    Product 1
1      2    Product 2
2      3    Product 3
3      4    Product 4
4      5    Product 5

############################################################

📊 DataFrame: df_Budget
============================================================
Shape : (30, 2)

Columns :
['Product Name', '2017 Budgets']

Missing Values :
Product Name    0
2017 Budgets    0
dtype: int64

Duplicate Rows : 0

Head :
  Product Name  2017 Budgets
0    Product 1   3016489.209
1    Product 2   3050087.565
2    Product 3   2642352.432
3    Product 4   2885560.824
4    Product 5   3925424.542

############################################################

# pandas profiling

In [45]:
import sys
print(sys.executable)

c:\Users\sidda\AppData\Local\Programs\Python\Python312\python.exe

# Data cleaning and Wrangling

- Data Cleaning = process of fixing or removing incorrect, missing, duplicate, or inconsistent data to improve data quality before analysis or machine learning.
    - Goal: make data accurate, consistent, and usable

- Data Wrangling = transforming raw data into a structured format suitable for analysis, visualization, and machine learning.
    - It focuses on:
        - combining datasets
        - reshaping data
        - grouping & aggregation
        - filtering & transforming values

### merging tables into one dataframe

In [46]:
df_sales.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270

In [47]:
df_Customers.head()

   Customer Index Customer Names
0               1  Geiss Company
1               2  Jaxbean Group
2               3     Ascend Ltd
3               4      Eire Corp
4               5   Blogtags Ltd

In [48]:
# merge sales with customers

df = df_sales.merge(
    df_Customers,
    how='left',
    left_on='Customer Name Index',
    right_on='Customer Index'
)

In [49]:
df.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost,Customer Index,Customer Names
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343,126,Rhynoodle Ltd
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918,96,Thoughtmix Ltd
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740,8,Amerisourc Corp
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852,42,Colgate-Pa Group
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270,73,Deseret Group

In [50]:
# merge with products

df = df.merge(
    df_Products,
    how='left',
    left_on='Product Description Index',
    right_on='Index'
)

In [51]:
df_Products.head()

   Index Product Name
0      1    Product 1
1      2    Product 2
2      3    Product 3
3      4    Product 4
4      5    Product 5

In [52]:
df.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost,Customer Index,Customer Names,Index,Product Name
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343,126,Rhynoodle Ltd,27,Product 27
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918,96,Thoughtmix Ltd,20,Product 20
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740,8,Amerisourc Corp,26,Product 26
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852,42,Colgate-Pa Group,7,Product 7
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270,73,Deseret Group,8,Product 8

In [53]:
# merge with regions
df = df.merge(
    df_Regions,
    how='left',
    left_on='Delivery Region Index',
    right_on='id'
)

In [54]:
df_Regions.head()

,id,name,county,state_code,state,type,latitude,longitude,area_code,population,households,median_income,land_area,water_area,time_zone
0,1,Auburn,Lee County,AL,Alabama,City,32.60986,-85.48078,334,62059,21767,38342,152375113,2646161,America/Chicago
1,2,Birmingham,Shelby County/Jefferson County,AL,Alabama,City,33.52744,-86.79905,205,212461,89972,31061,378353942,6591013,America/Chicago
2,3,Decatur,Limestone County/Morgan County,AL,Alabama,City,34.57332,-86.99214,256,55437,22294,41496,141006257,17594716,America/Chicago
3,4,Dothan,Dale County/Houston County/Henry County,AL,Alabama,City,31.23370,-85.40682,334,68567,25913,42426,232166237,835468,America/Chicago
4,5,Hoover,Shelby County/Jefferson County,AL,Alabama,City,33.37695,-86.80558,205,84848,32789,77146,122016784,2553332,America/Chicago

In [55]:
df

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,type,latitude,longitude,area_code,population,households,median_income,land_area,water_area,time_zone
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,City,32.08354,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,City,39.61366,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,City,37.66243,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,City,39.16533,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,Town,41.77524,-72.52443,959,58007,24141,63158,70972793,720300,America/New York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64099,SO - 0007573,2018-02-28,74,Wholesale,USD,AXW291,825,26,12,1815.7,...,CDP,40.15511,-74.82877,445,51326,18095,69878,26311722,253129,America/New York
64100,SO - 0007706,2018-02-28,51,Export,USD,NXH382,444,21,6,864.3,...,Village,42.11030,-88.03424,847,69308,26242,71573,35271964,370235,America/Chicago
64101,SO - 0007718,2018-02-28,136,Distributor,USD,AXW291,312,13,11,3953.0,...,City,26.24453,-80.20644,954,57234,20651,42786,22943340,594611,America/New York
64102,SO - 0008084,2018-02-28,158,Distributor,USD,AXW291,737,20,7,3959.7,...,Town,42.91002,-78.74182,716,87514,38912,48662,76228647,162756,America/New York
64103,SO - 0008654,2018-02-28,22,Distributor,USD,AXW291,807,15,8,998.3,...,City,45.48706,-122.80371,503,96577,37238,56882,50563936,0,America/Los Angeles

In [56]:
# merge with state Region

df = df.merge(
    df_state_regions[['State Code','Region']],
    how='left',
    left_on='state_code',
    right_on='State Code'
)

In [57]:
df_state_regions

0  State Code                 State     Region
0          AL               Alabama      South
1          AR              Arkansas      South
2          AZ               Arizona       West
3          CA            California       West
4          CO              Colorado       West
5          CT           Connecticut  Northeast
6          DC  District of Columbia      South
7          DE              Delaware      South
8          FL               Florida      South
9          GA               Georgia      South
10         HI                Hawaii       West
11         IA                  Iowa    Midwest
12         ID                 Idaho       West
13         IL              Illinois    Midwest
14         IN               Indiana    Midwest
15         KS                Kansas    Midwest
16         KY              Kentucky      South
17         LA             Louisiana      South
18         MA         Massachusetts  Northeast
19         MD              Maryland      South
20         ME                 Maine  Northeast
21         MI              Michigan    Midwest
22         MN             Minnesota    Midwest
23         MO              Missouri    Midwest
24         MS           Mississippi      South
25         MT               Montana       West
26         NC        North Carolina      South
27         ND          North Dakota    Midwest
28         NE              Nebraska    Midwest
29         NH         New Hampshire  Northeast
30         NJ            New Jersey  Northeast
31         NM            New Mexico       West
32         NV                Nevada       West
33         NY              New York  Northeast
34         OH                  Ohio    Midwest
35         OK              Oklahoma      South
36         OR                Oregon       West
37         PA          Pennsylvania  Northeast
38         RI          Rhode Island  Northeast
39         SC        South Carolina      South
40         SD          South Dakota    Midwest
41         TN             Tennessee      South
42         TX                 Texas      South
43         UT                  Utah       West
44         VA              Virginia      South
45         WA            Washington       West
46         WI             Wisconsin    Midwest
47         WY               Wyoming       West

In [58]:
df

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,longitude,area_code,population,households,median_income,land_area,water_area,time_zone,State Code,Region
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York,GA,South
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,IN,Midwest
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles,CA,West
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,IN,Midwest
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,-72.52443,959,58007,24141,63158,70972793,720300,America/New York,CT,Northeast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64099,SO - 0007573,2018-02-28,74,Wholesale,USD,AXW291,825,26,12,1815.7,...,-74.82877,445,51326,18095,69878,26311722,253129,America/New York,PA,Northeast
64100,SO - 0007706,2018-02-28,51,Export,USD,NXH382,444,21,6,864.3,...,-88.03424,847,69308,26242,71573,35271964,370235,America/Chicago,IL,Midwest
64101,SO - 0007718,2018-02-28,136,Distributor,USD,AXW291,312,13,11,3953.0,...,-80.20644,954,57234,20651,42786,22943340,594611,America/New York,FL,South
64102,SO - 0008084,2018-02-28,158,Distributor,USD,AXW291,737,20,7,3959.7,...,-78.74182,716,87514,38912,48662,76228647,162756,America/New York,NY,Northeast
64103,SO - 0008654,2018-02-28,22,Distributor,USD,AXW291,807,15,8,998.3,...,-122.80371,503,96577,37238,56882,50563936,0,America/Los Angeles,OR,West

In [59]:
# merge with budget

df = df.merge(
    df_Budget,
    how='left',
    on='Product Name'
)

In [60]:
df.head()


# mearging completed

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,area_code,population,households,median_income,land_area,water_area,time_zone,State Code,Region,2017 Budgets
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,912,145674,52798,36466,268318796,13908113,America/New York,GA,South,964940.231
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,IN,Midwest,2067108.120
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,925,79510,26020,124759,62489257,386195,America/Los Angeles,CA,West,5685138.270
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,IN,Midwest,889737.555
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,959,58007,24141,63158,70972793,720300,America/New York,CT,Northeast,1085037.329

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Index             64104 non-null  int64
 13  Customer Names             64104 non-null  object
 14  Index                      64104 non-null  int64
 15  Product Name               64104 non-null  object
 16  id                         64104 non-null  int64
 17  name                       64104 non-null  object
 18  county                     64104 non-null  object
 19  state_code                 64104 non-null  object
 20  state                      64104 non-null  object
 21  type                       64104 non-null  object
 22  latitude                   64104 non-null  float64
 23  longitude                  64104 non-null  float64
 24  area_code                  64104 non-null  int64
 25  population                 64104 non-null  int64
 26  households                 64104 non-null  int64
 27  median_income              64104 non-null  int64
 28  land_area                  64104 non-null  int64
 29  water_area                 64104 non-null  int64
 30  time_zone                  64104 non-null  object
 31  State Code                 64104 non-null  object
 32  Region                     64104 non-null  object
 33  2017 Budgets               64104 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(13), object(14)
memory usage: 16.6+ MB

In [62]:
df.columns

Index(['OrderNumber', 'OrderDate', 'Customer Name Index', 'Channel',
       'Currency Code', 'Warehouse Code', 'Delivery Region Index',
       'Product Description Index', 'Order Quantity', 'Unit Price',
       'Line Total', 'Total Unit Cost', 'Customer Index', 'Customer Names',
       'Index', 'Product Name', 'id', 'name', 'county', 'state_code', 'state',
       'type', 'latitude', 'longitude', 'area_code', 'population',
       'households', 'median_income', 'land_area', 'water_area', 'time_zone',
       'State Code', 'Region', '2017 Budgets'],
      dtype='object')

In [63]:
Df_lst= df.columns.to_list()

In [64]:
df.isnull().sum().sum()

np.int64(0)

In [65]:
df.duplicated().sum()

np.int64(0)

In [66]:
df.columns.duplicated().sum()

np.int64(0)

In [67]:
df.to_csv('temp_file.csv') # just to store the merged dataframe before forther cleaning

In [68]:
df.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,area_code,population,households,median_income,land_area,water_area,time_zone,State Code,Region,2017 Budgets
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,912,145674,52798,36466,268318796,13908113,America/New York,GA,South,964940.231
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,IN,Midwest,2067108.120
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,925,79510,26020,124759,62489257,386195,America/Los Angeles,CA,West,5685138.270
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,IN,Midwest,889737.555
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,959,58007,24141,63158,70972793,720300,America/New York,CT,Northeast,1085037.329

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Index             64104 non-null  int64
 13  Customer Names             64104 non-null  object
 14  Index                      64104 non-null  int64
 15  Product Name               64104 non-null  object
 16  id                         64104 non-null  int64
 17  name                       64104 non-null  object
 18  county                     64104 non-null  object
 19  state_code                 64104 non-null  object
 20  state                      64104 non-null  object
 21  type                       64104 non-null  object
 22  latitude                   64104 non-null  float64
 23  longitude                  64104 non-null  float64
 24  area_code                  64104 non-null  int64
 25  population                 64104 non-null  int64
 26  households                 64104 non-null  int64
 27  median_income              64104 non-null  int64
 28  land_area                  64104 non-null  int64
 29  water_area                 64104 non-null  int64
 30  time_zone                  64104 non-null  object
 31  State Code                 64104 non-null  object
 32  Region                     64104 non-null  object
 33  2017 Budgets               64104 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(13), object(14)
memory usage: 16.6+ MB

In [70]:
# checking duplicate columns values

for i in range(len(df.columns)):
    for j in range(i+1, len(df.columns)):

        col1 = df.columns[i]
        col2 = df.columns[j]

        if df[col1].equals(df[col2]):

            print(f"Same values -> {col1} & {col2}")

Same values -> Customer Name Index & Customer Index
Same values -> Delivery Region Index & id
Same values -> Product Description Index & Index
Same values -> state_code & State Code

In [71]:
duplicate_value_columns = []

for i in range(len(df.columns)):
    for j in range(i+1, len(df.columns)):

        col1 = df.columns[i]
        col2 = df.columns[j]

        if df[col1].equals(df[col2]):

            duplicate_value_columns.append((col1, col2))

duplicate_value_columns

[('Customer Name Index', 'Customer Index'),
 ('Delivery Region Index', 'id'),
 ('Product Description Index', 'Index'),
 ('state_code', 'State Code')]

In [72]:
### we have to drop the duplicate columns

[('Customer Name Index', 'Customer Index'),
 ('Delivery Region Index', 'id'),
 ('Product Description Index', 'Index'),
 ('state_code', 'State Code')]

[('Customer Name Index', 'Customer Index'),
 ('Delivery Region Index', 'id'),
 ('Product Description Index', 'Index'),
 ('state_code', 'State Code')]

In [73]:
# from ('Customer Name Index', 'Customer Index') ------> Customer Index
# from ('Product Description Index', 'Index') ----------> Index
# from ('Delivery Region Index', 'id') -------> id
# from ('state_code', 'State Code') -------> State Code

# Clean up redundant columns

cols_to_drop = ['Customer Index', 'Index', 'id', 'State Code']

df = df.drop(columns=cols_to_drop, errors='ignore')

df.head(5)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,longitude,area_code,population,households,median_income,land_area,water_area,time_zone,Region,2017 Budgets
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York,South,964940.231
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,Midwest,2067108.120
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles,West,5685138.270
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,Midwest,889737.555
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,-72.52443,959,58007,24141,63158,70972793,720300,America/New York,Northeast,1085037.329

In [74]:
df

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,longitude,area_code,population,households,median_income,land_area,water_area,time_zone,Region,2017 Budgets
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York,South,964940.231
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,Midwest,2067108.120
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles,West,5685138.270
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,Midwest,889737.555
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,-72.52443,959,58007,24141,63158,70972793,720300,America/New York,Northeast,1085037.329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64099,SO - 0007573,2018-02-28,74,Wholesale,USD,AXW291,825,26,12,1815.7,...,-74.82877,445,51326,18095,69878,26311722,253129,America/New York,Northeast,5685138.270
64100,SO - 0007706,2018-02-28,51,Export,USD,NXH382,444,21,6,864.3,...,-88.03424,847,69308,26242,71573,35271964,370235,America/Chicago,Midwest,959899.218
64101,SO - 0007718,2018-02-28,136,Distributor,USD,AXW291,312,13,11,3953.0,...,-80.20644,954,57234,20651,42786,22943340,594611,America/New York,South,3720639.645
64102,SO - 0008084,2018-02-28,158,Distributor,USD,AXW291,737,20,7,3959.7,...,-78.74182,716,87514,38912,48662,76228647,162756,America/New York,Northeast,2067108.120
64103,SO - 0008654,2018-02-28,22,Distributor,USD,AXW291,807,15,8,998.3,...,-122.80371,503,96577,37238,56882,50563936,0,America/Los Angeles,West,3299478.315

In [75]:
# covertion all column values to lower case for consistencity and easier access

df.columns = df.columns.str.lower()
df.columns

Index(['ordernumber', 'orderdate', 'customer name index', 'channel',
       'currency code', 'warehouse code', 'delivery region index',
       'product description index', 'order quantity', 'unit price',
       'line total', 'total unit cost', 'customer names', 'product name',
       'name', 'county', 'state_code', 'state', 'type', 'latitude',
       'longitude', 'area_code', 'population', 'households', 'median_income',
       'land_area', 'water_area', 'time_zone', 'region', '2017 budgets'],
      dtype='object')

In [76]:
df.to_csv('cleaned_Regional_sales_df_with_all_columns.csv')

In [77]:
# Drop un-necessary columns 

 # List only the columns you want to KEEP, now including the broader 'region'
cols_to_keep = [
    'ordernumber',        # unique order ID
    'orderdate',          # date when the order was placed
    'customer names',     # customer who placed the order
    'channel',            # sales channel (e.g., Wholesale, Distributor)
    'product name',       # product purchased
    'order quantity',     # number of units ordered
    'unit price',         # price per unit
    'line total',         # revenue for this line item (qty × unit_price)
    'total unit cost',    # company’s cost for this line item
    'state_code',         # two-letter state code
    'state',              # full state name
    'region',             # broader U.S. region (e.g., South, West)
    'latitude',           # latitude of delivery city
    'longitude',          # longitude of delivery city
    '2017 budgets'        # budget target for this product in 2017
]

In [78]:
# Subset the DataFrame to only these columns

df = df[cols_to_keep]

In [79]:
df.head()

,ordernumber,orderdate,customer names,channel,product name,order quantity,unit price,line total,total unit cost,state_code,state,region,latitude,longitude,2017 budgets
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Georgia,South,32.08354,-81.09983,964940.231
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Indiana,Midwest,39.61366,-86.10665,2067108.120
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,California,West,37.66243,-121.87468,5685138.270
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Indiana,Midwest,39.16533,-86.52639,889737.555
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Connecticut,Northeast,41.77524,-72.52443,1085037.329

In [80]:
 # Rename to more Pythonic / self-explanatory names

df = df.rename(columns={
    'ordernumber'      : 'order_number',   # snake_case for consistency
    'orderdate'        : 'order_date',     # date of the order
    'customer names'   : 'customer_name',  # customer who placed it
    'product name'     : 'product_name',   # product sold
    'order quantity'   : 'quantity',       # units sold
    'unit price'       : 'unit_price',     # price per unit in USD
    'line total'       : 'revenue',        # revenue for the line item
    'total unit cost'  : 'cost',           # cost for the line item
    'state_code'       : 'state',          # two-letter state code
    'state'            : 'state_name',     # full state name
    'region'           : 'us_region',      # broader U.S. region
    'latitude'         : 'lat',            # latitude (float)
    'longitude'        : 'lon',            # longitude (float)
    '2017 budgets'     : 'budget'          # 2017 budget target (float)
})

In [81]:
df.head()

,order_number,order_date,customer_name,channel,product_name,quantity,unit_price,revenue,cost,state,state_name,us_region,lat,lon,budget
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Georgia,South,32.08354,-81.09983,964940.231
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Indiana,Midwest,39.61366,-86.10665,2067108.120
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,California,West,37.66243,-121.87468,5685138.270
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Indiana,Midwest,39.16533,-86.52639,889737.555
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Connecticut,Northeast,41.77524,-72.52443,1085037.329

In [82]:
# Blank out budgets for non-2017 orders
df.loc[df['order_date'].dt.year != 2017, 'budget'] = pd.NA

In [83]:

# Inspect
df[['order_date','product_name','revenue','budget']].head(10)

  order_date product_name  revenue  budget
0 2014-01-01   Product 27  14994.6     NaN
1 2014-01-01   Product 20  25868.7     NaN
2 2014-01-01   Product 26   5869.2     NaN
3 2014-01-01    Product 7  16368.1     NaN
4 2014-01-01    Product 8  18331.2     NaN
5 2014-01-01   Product 23  57412.3     NaN
6 2014-01-01    Product 1  20120.1     NaN
7 2014-01-01   Product 25  10452.0     NaN
8 2014-01-01   Product 13  19262.5     NaN
9 2014-01-01   Product 14  34974.0     NaN

In [84]:
df.isnull().sum()

order_number         0
order_date           0
customer_name        0
channel              0
product_name         0
quantity             0
unit_price           0
revenue              0
cost                 0
state                0
state_name           0
us_region            0
lat                  0
lon                  0
budget           48841
dtype: int64

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_number   64104 non-null  object
 1   order_date     64104 non-null  datetime64[ns]
 2   customer_name  64104 non-null  object
 3   channel        64104 non-null  object
 4   product_name   64104 non-null  object
 5   quantity       64104 non-null  int64
 6   unit_price     64104 non-null  float64
 7   revenue        64104 non-null  float64
 8   cost           64104 non-null  float64
 9   state          64104 non-null  object
 10  state_name     64104 non-null  object
 11  us_region      64104 non-null  object
 12  lat            64104 non-null  float64
 13  lon            64104 non-null  float64
 14  budget         15263 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(7)
memory usage: 7.3+ MB

In [86]:
df.to_csv('final_cleaned_sales_df.csv', index=False)

In [87]:
df_2017 = df[df['order_date'].dt.year ==2017]

In [88]:
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15263 entries, 46363 to 61625
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_number   15263 non-null  object
 1   order_date     15263 non-null  datetime64[ns]
 2   customer_name  15263 non-null  object
 3   channel        15263 non-null  object
 4   product_name   15263 non-null  object
 5   quantity       15263 non-null  int64
 6   unit_price     15263 non-null  float64
 7   revenue        15263 non-null  float64
 8   cost           15263 non-null  float64
 9   state          15263 non-null  object
 10  state_name     15263 non-null  object
 11  us_region      15263 non-null  object
 12  lat            15263 non-null  float64
 13  lon            15263 non-null  float64
 14  budget         15263 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(7)
memory usage: 1.9+ MB

In [89]:
df_2017.head()

,order_number,order_date,customer_name,channel,product_name,quantity,unit_price,revenue,cost,state,state_name,us_region,lat,lon,budget
46363,SO - 0002544,2017-01-01,NCS Group,Wholesale,Product 30,6,1239.5,7437.0,1028.785,NJ,New Jersey,Northeast,40.77955,-74.02375,1011609.684
46364,SO - 0006431,2017-01-01,Epic Group,Wholesale,Product 13,5,1829.1,9145.5,1207.206,CO,Colorado,West,39.06387,-108.55065,3720639.645
46365,SO - 0007491,2017-01-01,State Ltd,Wholesale,Product 15,9,2412.0,21708.0,1664.280,CA,California,West,33.96168,-118.35313,3299478.315
46366,SO - 0008741,2017-01-01,Fivebridge Ltd,Wholesale,Product 8,8,904.5,7236.0,750.735,IA,Iowa,Midwest,42.50056,-90.66457,1085037.329
46367,SO - 0009295,2017-01-01,Tagfeed Ltd,Wholesale,Product 2,12,1112.2,13346.4,811.906,FL,Florida,South,28.47689,-82.52546,3050087.565

In [90]:
df_2017.isnull().sum()

order_number     0
order_date       0
customer_name    0
channel          0
product_name     0
quantity         0
unit_price       0
revenue          0
cost             0
state            0
state_name       0
us_region        0
lat              0
lon              0
budget           0
dtype: int64

## Feature Engineering

In [91]:
df.head()

,order_number,order_date,customer_name,channel,product_name,quantity,unit_price,revenue,cost,state,state_name,us_region,lat,lon,budget
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Georgia,South,32.08354,-81.09983,NaN
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Indiana,Midwest,39.61366,-86.10665,NaN
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,California,West,37.66243,-121.87468,NaN
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Indiana,Midwest,39.16533,-86.52639,NaN
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Connecticut,Northeast,41.77524,-72.52443,NaN

In [92]:
# 1. Calculate total cost for each line item
df['total_cost'] = df['quantity'] * df['cost']

In [93]:
# 2. Calculate profit as revenue minus total_cost
df['profit'] = df['revenue'] - df['total_cost']

In [94]:
# 3. Calculate profit margin as a percentage
df['profit_margin_pct'] = (df['profit'] / df['revenue']) * 100

In [95]:
# 4. Extract full month name from order_date for labeling (e.g., 'January', 'February')
df['order_month_name'] = df['order_date'].dt.month_name()

In [96]:
# 5. Extract month number from order_date for correct sorting (1–12)
df['order_month_num'] = df['order_date'].dt.month

In [97]:
# Display the updated DataFrame
df

,order_number,order_date,customer_name,channel,product_name,quantity,unit_price,revenue,cost,state,state_name,us_region,lat,lon,budget,total_cost,profit,profit_margin_pct,order_month_name,order_month_num
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Georgia,South,32.08354,-81.09983,NaN,10946.058,4048.542,27.0,January,1
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Indiana,Midwest,39.61366,-86.10665,NaN,13969.098,11899.602,46.0,January,1
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,California,West,37.66243,-121.87468,NaN,4108.440,1760.760,30.0,January,1
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Indiana,Midwest,39.16533,-86.52639,NaN,7201.964,9166.136,56.0,January,1
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Connecticut,Northeast,41.77524,-72.52443,NaN,10082.160,8249.040,45.0,January,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64099,SO - 0007573,2018-02-28,Dazzlesphe Corp,Wholesale,Product 26,12,1815.7,21788.4,980.478,PA,Pennsylvania,Northeast,40.15511,-74.82877,NaN,11765.736,10022.664,46.0,February,2
64100,SO - 0007706,2018-02-28,Yombu Corp,Export,Product 21,6,864.3,5185.8,579.081,IL,Illinois,Midwest,42.11030,-88.03424,NaN,3474.486,1711.314,33.0,February,2
64101,SO - 0007718,2018-02-28,Bath Group,Distributor,Product 13,11,3953.0,43483.0,2648.510,FL,Florida,South,26.24453,-80.20644,NaN,29133.610,14349.390,33.0,February,2
64102,SO - 0008084,2018-02-28,Linklinks Ltd,Distributor,Product 20,7,3959.7,27717.9,2930.178,NY,New York,Northeast,42.91002,-78.74182,NaN,20511.246,7206.654,26.0,February,2
64103,SO - 0008654,2018-02-28,SAFEWAY Ltd,Distributor,Product 15,8,998.3,7986.4,848.555,OR,Oregon,West,45.48706,-122.80371,NaN,6788.440,1197.960,15.0,February,2